version: "1.0"

services:
  app:
    build:
      dockerfile: development.Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db-net

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - db-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - db-net

volumes:
  db:

networks:
  db-net: