version: "1.0"

services:
  app:
    build:
      dockerfile: development.Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=dbadmin
      - DB_PASSWORD=keyboard
      - DB_NAME=medical-clinic
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - db-net

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: keyboard
      POSTGRES_DB: medical-clinic
    ports:
      - 5432:5432
    networks:
      - db-net
    healthcheck:
        test: /usr/bin/pg_isready -d medical-clinic -U dbadmin
        interval: 5s
        timeout: 10s
        retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - db-net

volumes:
  db:

networks:
  db-net: