// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Doctor              string
	Genericuser         string
	GooseDBVersion      string
	Insurances          string
	Insurancesondoctor  string
	Insurancesonpatient string
	Insurancesonuser    string
	Patient             string
	Roles               string
	Rolesonuser         string
	Specialties         string
	Specialtiesondoctor string
}{
	Doctor:              "doctor",
	Genericuser:         "genericuser",
	GooseDBVersion:      "goose_db_version",
	Insurances:          "insurances",
	Insurancesondoctor:  "insurancesondoctor",
	Insurancesonpatient: "insurancesonpatient",
	Insurancesonuser:    "insurancesonuser",
	Patient:             "patient",
	Roles:               "roles",
	Rolesonuser:         "rolesonuser",
	Specialties:         "specialties",
	Specialtiesondoctor: "specialtiesondoctor",
}
